/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * DemoApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface WeatherForecast {
  date?: string;
  temperatureC?: number;
  temperatureF?: number;
  /** @nullable */
  summary?: string | null;
}
