/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * DemoApi | v1
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  WeatherForecast
} from './model';




  export const getWeatherForecast = <TData = AxiosResponse<WeatherForecast[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/WeatherForecast`,options
    );
  }

export type GetWeatherForecastResult = AxiosResponse<WeatherForecast[]>
